### ISSUE TITLE
Include an example demonstrating QtMaterial please!

### ISSUE THREAD

**Issue by shujaatak** [mahdi139091/QtMaterial#1]

**Comment by Daguerreo** [comment]
> _No description provided._

I agree

**Comment by miangoleh** [comment]
I will add some examples Within few days.
Meanwhile you can refer to link i added in Rep. title and see the example there. I have added some functionallity that i would show it later with examples

**Comment by miangoleh** [comment]
now SetIconSize in IconButton / ToggleButton / CheckBox works
you can set BgColor for IconButton
i create a new Class nemed hoverStateMachine that you can use in any other class to perform animations on Enter/Leave or show/hide events
you can setContentMargin for FlatButton
some extra theme Role parameters added because of my needs.

**Comment by Daguerreo** [comment]
What's the point in this comment? And wy did you close it?
