### ISSUE TITLE
Insert Screenshots and Example code

### ISSUE THREAD

**Issue by Daguerreo** [mahdi139091/QtMaterial#2]
Include something to demonstrate what your code can do

**Comment by miangoleh** [comment]
I will add some examples Within few days.
Meanwhile you can refer to link i added in Rep. title and see the example there. I have added some functionallity that i would show it later with examples

**Comment by Daguerreo** [comment]
> I will add some examples Within few days.
> Meanwhile you can refer to link i added in Rep. title and see the example there. I have added some functionallity that i would show it later with examples

We know what laserpants's project can do. You should show the extras of yours

**Comment by miangoleh** [comment]
now SetIconSize in IconButton / ToggleButton / CheckBox works
you can set BgColor for IconButton
i create a new Class nemed hoverStateMachine that you can use in any other class to perform animations on Enter/Leave or show/hide events
you can setContentMargin for FlatButton
some extra theme Role parameters added because of my needs.
